name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Build Common
      run: dotnet build --configuration Release ./src/RapidCMS.Common/RapidCMS.Common.csproj
    - name: Build Repositories
      run: dotnet build --configuration Release ./src/RapidCMS.Repositories/RapidCMS.Repositories.csproj
    - name: Build UI
      run: dotnet build --configuration Release ./src/RapidCMS.UI/RapidCMS.UI.csproj

  release:

    runs-on: ubuntu-latest

    steps:
    - name: Authenticate
      run: nuget source Add -Name "GitHub" -Source "https://nuget.pkg.github.com/ThomasBleijendaal/index.json" -UserName ThomasBleijendaal -Password GH_TOKEN